<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=about">À propos</a>
					</li>
					<li>
						<a href="index.php?route=contact">Contact</a>
					</li>
				</ul>
			</nav>
		</header>
    <?php

    if($route === "home")
    {
        require_once "templates/home.phtml";
    }
    else if($route === "about")
    {
        require_once "templates/about.phtml";
    }
    else if($route === "contact")
    {
        require_once "templates/contact.phtml";
    }
    elseif($route === "404")
    {
        require_once "templates/404.phtml";
    }
    
    ?>
	</body>
</html>